baseURL = 'https://liuzhanpeng.github.io/'
languageCode = 'en-us'
title = "Parker's learning"
publishDir = 'docs'

theme = 'gokarna'

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

[params]
    description = "Hello, world!"
    showPostsOnHomePage = "recent"